# Generated by Django 4.0 on 2023-04-29 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profiles/default_profile_image.jpg', upload_to='profiles/'),
        ),
    ]
